name: DespairDifficulty
version: '${project.version}'
main: despairdifficulty.despairdifficulty.DespairDifficulty
api-version: 1.19
authors: [ Herculuke ]
description: The most impossible plugin to beat in survival Minecraft, you have two lives to beat the game, good luck!
